version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: storage_db
    restart: always
    ports:
      - "5433:5432"
    environment:
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_DB: ${POSTGRES_DB}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
